version: '3'
services:
  web:
    image: nginx:alpine
    container_name: da-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
      - ./logs/nginx:/var/log/nginx/
    links:
      - app
      - database
      - redis

  app:
    # image: php:7.2-fpm-alpine
    build: ./conf/php
    container_name: da-php
    working_dir: /app
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/php/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./app:/app
      - ./logs:/app/storage/logs
  
  database:
    image: mysql
    container_name: da-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  redis:
    image: redis:alpine
    container_name: da-redis
    volumes:
      - ./data/db/redis:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
